name: "Hello Actions"
description: "Greet someone"

inputs:
  MY_NAME:
    description: "Es mi nombre"
    required: true
    default: "World"

runs:
  using: "Docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
