name: "Hello Actions"
description: "Prueba"
author: "octocat@github.com"

inputs:
  MY_NAM:
    description: "Who to greet"
    required: true
    default: "Karen Manrique"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
