name: A workflow for my Hello World file
on: [push, pull_request]

jobs:
  apply:
    name: corriendo accion a
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Accion a
        uses: ./action-a
        with:
          MY_NAME: "Yeison Orlando Manrique Rojas"
      - name: Accion b
        uses: ./action-b
        with:
          MY_NAM: "prueba"
  build:
    name: corriendo accion b
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Accion b
        uses: ./action-b
        with:
          MY_NAM: "prueba"
  
