name: A workflow for my Hello World file
on: [push, pull_request]

#on:
#  pull_request:
#    branches:
#      - qa

#on:
#  schedule:
#    - cron:  '*/15 * * * *'

jobs:
  apply:
    name: corriendo accion a
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [6, 8, 10]
        name: 
          - "yeison"
          - "orlando" 
          - "manrique"
        exclude:
        - os: windows-latest
          #node: 6
        - os: macos-latest
        
    #runs-on: ubuntu-latest    
    runs-on: ${{matrix.os}}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Accion a
        uses: ./action-a
        with:
          MY_NAME: ${{matrix.name}}
          
      - name: Accion b
        uses: ./action-b
        with:
          MY_NAM: ${{secrets.NAME_TEST}}
      
      - name: node config
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
          
#      - name: npm install
#        run: npm install
#        shell: bash

  build:
    name: corriendo accion b
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Accion b
        uses: ./action-b
        with:
          MY_NAM: "prueba"
  test:
    name: corriendo accion b - > a
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Accion a
        uses: ./action-a
        with:
          MY_NAM: "prueba"
  
