name: A workflow for my Hello World file
on: [push, pull_request]

#on:
#  pull_request:
#    branches:
#      - qa

#on:
#  schedule:
#    - cron:  '0 15 * * 2'

jobs:
  apply:
    name: corriendo accion a
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Accion a
        uses: ./action-a
        with:
          MY_NAME: "Yeison Orlando Manrique Rojas"
      - name: Accion b
        uses: ./action-b
        with:
          MY_NAM: "prueba"
          
#      - name: npm install
#        run: npm install
#        shell: bash

  build:
    name: corriendo accion b
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Accion b
        uses: ./action-b
        with:
          MY_NAM: "prueba"
  test:
    name: corriendo accion a - > b
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Accion b
        uses: ./action-b
        with:
          MY_NAM: "prueba"
  
